# Computation on NumPy Arrays

### Array arithmetic: Universal Functions

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators. NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called *universal functions*(ufunc).
The standard addition, subtraction, multiplication, and division can all be used:

In [23]:
import numpy as np
x = np.arange(4)
print("x     =", x)       
print("x + 5 =", x + 5)    # add
print("x - 5 =", x - 5)    # subtract
print("x * 2 =", x * 2)    # multiply
print("x / 2 =", x / 2)    # divide 
print("x ^ 2 =", x ** 2)   # exponentiate
print("-x    =", -x)       # unary negation

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x ^ 2 = [0 1 4 9]
-x    = [ 0 -1 -2 -3]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [9]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the ``+`` operator is a wrapper for the ``add`` function:

In [10]:
np.add(x, 2)

array([2, 3, 4, 5])

### Absolute value

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [11]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is ``np.absolute``, which is also available under the alias ``np.abs``:

In [12]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [13]:
np.abs(x)

array([2, 1, 0, 1, 2])

### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [24]:
x1 = [1, 2, 3]
print("x1     =", x1)
print("e^x1   =", np.exp(x1))
print("2^x1   =", np.exp2(x1))
print("3^x1   =", np.power(3, x1))

x1     = [1, 2, 3]
e^x1   = [  2.71828183   7.3890561   20.08553692]
2^x1   = [ 2.  4.  8.]
3^x1   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [15]:
x2 = [1, 2, 4, 10]
print("x2        =", x2)
print("ln(x2)    =", np.log(x2))
print("log2(x2)  =", np.log2(x2))
print("log10(x2) =", np.log10(x2))

x2        = [1, 2, 4, 10]
ln(x2)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x2)  = [ 0.          1.          2.          3.32192809]
log10(x2) = [ 0.          0.30103     0.60205999  1.        ]


### Aggregations: Min, Max, and Everything In Between

In [25]:
L = np.random.random(100)
sum(L)

50.578528227921197

In [26]:
np.sum(L)

50.57852822792119

In [27]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 3: 83.3 ms per loop
1000 loops, best of 3: 508 µs per loop


For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [30]:
print(big_array.min(), 
      big_array.max(), 
      big_array.sum())

1.70431272495e-06 0.999999809342 500221.870271


### Multi dimensional aggregates

In [31]:
M = np.random.random((3, 4))
print(M)

[[ 0.69232104  0.66140846  0.30347013  0.32790361]
 [ 0.53974282  0.86462229  0.57605462  0.43283813]
 [ 0.68101857  0.39312451  0.50400735  0.9184384 ]]


In [32]:
M.sum()

6.8949499271968415

Other useful aggregation functions available in NumPy:

In [38]:
print(M.mean(),
      M.std(),
      M.var(),
      M.min(),
      M.max())

0.5745791606 0.189001188298 0.0357214491779 0.30347013214 0.91843840491
